version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dnd-8th-4-backend   # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user