version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dnd-8th-4-backend   # 프로젝트 이름
    overwrite: yes

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 60
      runas: ec2-user
    - location: scripts/health_check.sh
      timeout: 60
      runas: ec2-user
    - location: scripts/switch.sh
      timeout: 60
      runas: ec2-user